version: 2.1
orbs:
  heroku: circleci/heroku@2.0
workflows:
  test-backend:
    jobs:
      - unit-test-backend
  build-eslint-deploy:
    jobs:
      - build-eslint-deploy-frontend:
          filters:
            branches:
              only:
                - main
      - deploy-backend:
          filters:
            branches:
              only:
                - main

jobs:
  unit-test-backend:
    docker:
        - image: cimg/node:16.13.2
    parallelism: 4
    steps:
      - checkout
      - run:
          name: Install JUnit coverage reporter
          command: cd Backend/nest-graphql-backend && npm i --dev jest-junit
      - run:
          name: Install Backend Dependencies
          command: cd Backend/nest-graphql-backend && npm install
      - save_cache:
          key: dependency-cache-{{ checksum "Backend/nest-graphql-backend/package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Run tests with JUnit as reporter
          command: cd Backend/nest-graphql-backend && yarn run test
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/
      - store_artifacts:
          path: ./Backend/nest-graphql-backend/coverage/lcov-report/index.html
          path: ./Backend/nest-graphql-backend/coverage/lcov-report/base.css
          path: ./Backend/nest-graphql-backend/coverage/lcov-report/prettify.css
          path: ./Backend/nest-graphql-backend/coverage/lcov-report/favicon.png
      - store_test_results:
          path: ./Backend/nest-graphql-backend/reports
  build-eslint-deploy-frontend:
    docker:
      - image: cimg/node:16.13.2
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "sudo npm install -g npm"
      - restore_cache:
          key: dependency-cache-{{ checksum "Frontend/masterfrontend/package-lock.json" }}
      - run:
          name: Install Frontend Frontend Dependencies
          command: cd Frontend/masterfrontend && npm install
      - save_cache:
          key: dependency-cache-{{ checksum "Frontend/masterfrontend/package-lock.json" }}
          paths:
            - Frontend/masterfrontend/node_modules
      - run:
          name: Run eslint
          command: cd Frontend/masterfrontend && npm run lint
      - run:
          name: Build React App
          command: cd Frontend/masterfrontend && npm run build
      - save_cache:
          key: app-build-cache-{{ .Branch }}
          paths:
            - Frontend/masterfrontend/build
  deploy-backend:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git