version: 2.1
orbs:
  heroku: circleci/heroku@1.2.6
workflows:
  build-deploy:
    jobs:
      - build-frontend
      - build-backend
      - deploy-frontend:
          requires:
            - build-frontend
          filters:
            branches:
              only:
                - main
      - deploy-backend:
          filters:
            branches:
              only:
                - main

jobs:
  build-frontend:
    docker:
      - image: cimg/node:16.13.2
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "sudo npm install -g npm"
      - restore_cache:
          key: dependency-cache-{{ checksum "Frontend/masterfrontend/package-lock.json" }}
      - run:
          name: Install Frontend Dependencies
          command: cd Frontend/masterfrontend && npm install
      - save_cache:
          key: dependency-cache-{{ checksum "Frontend/masterfrontend/package-lock.json" }}
          paths:
            - Frontend/masterfrontend/node_modules
      - run:
          name: Build React App
          command: cd Frontend/masterfrontend && npm run build
      - save_cache:
          key: app-build-cache-{{ .Branch }}
          paths:
            - Frontend/masterfrontend/build
  build-backend:
    docker:
      - image: cimg/node:16.13.2
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "sudo npm install -g npm"
      - restore_cache:
          key: dependency-cache-{{ checksum "Backend/nest-graphql-backend/package-lock.json" }}
      - run:
          name: Install Backend Dependencies
          command: cd Backend/nest-graphql-backend && npm install
      - save_cache:
          key: dependency-cache-{{ checksum "Backend/nest-graphql-backend/package-lock.json" }}
          paths:
            - Backend/nest-graphql-backend/node_modules
      - run:
          name: Build Nest App
          command: cd Backend/nest-graphql-backend && npm run build
      - save_cache:
          key: app-build-cache-{{ .Branch }}
          paths:
            - Backend/nest-graphql-backend/build
  deploy-backend:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git
  deploy-frontend:
    docker:
      - image: cimg/node:16.13.2
    steps:
      - checkout
      - run:
          name: Deploy to Netlify
          command: cd Frontend/masterfrontend && ./node_modules/.bin/netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --prod --dir=build
